In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [7]:
my_lists = [my_list1, my_list2]

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape

(2, 4)

In [12]:
my_array2.dtype

dtype('int64')

In [13]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
my_zeros = np.zeros(5)

In [15]:
my_zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [22]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

empty ≠ zero なので、適当な数値が入ってしまっている…　いた、何故か0で初期化されていた入りする

In [25]:
np.empty((4,5))

array([[  6.93241911e-310,   2.34257550e-316,   0.00000000e+000,
          0.00000000e+000,   6.93234805e-310],
       [  3.94356143e+180,   1.68750160e+160,   1.18948175e-047,
          5.18612274e+170,   1.88033430e+160],
       [  7.48951808e-144,   6.01433264e+175,   6.93885958e+218,
          5.56218858e+180,   1.50008929e+248],
       [  4.50620083e-144,   5.22689326e-143,   8.26661476e-072,
          2.42295123e-028,   2.17462508e-076]])

In [26]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(7,200,20)

array([  7,  27,  47,  67,  87, 107, 127, 147, 167, 187])